### ISSUE TITLE
Update references "git" -> "GitHub"

### ISSUE THREAD

**Issue by cassgvp** [cassgvp/git-for-collaborative-documentation#20]
Check that I am using "GitHub" in all correct instances where I've just written "git"

**Comment by Ruth-ikegah** [comment]
Hi, @cassgvp Please I will love to tackle this issue. I have a question. On what file path am I updating the references. I know the two places I see git used is on the readme file, the title, and the thank you section.

**Comment by cassgvp** [comment]
Hi @Ruth-ikegah! Many thanks for looking into this! 

The screenshot below shows all files with instances of the word "git". Some of these may be appropriate, for example "git status", but other not. Would be great if you could change the ones you think were appropriate! 

![Screenshot 2020-10-09 at 13 54 43](https://user-images.githubusercontent.com/43407869/95585326-fdf2ed80-0a36-11eb-84ce-849a568b21bb.png)

**Comment by Ruth-ikegah** [comment]
Okay thanks @cassgvp I will go ahead with my search and send a PR
